/**
 * R2 credentials configuration
 * Uses embedded credentials from build time, or falls back to environment variables
 */

// Import embedded credentials (generated at build time from your .env)
// This file is generated by scripts/embed-r2-credentials.js during build
import { R2_CREDENTIALS as EMBEDDED_CREDENTIALS } from "./r2-credentials-embedded.js";

export interface R2Credentials {
  endpoint: string;
  accessKey: string;
  secretKey: string;
  bucket: string;
}

export function getR2Credentials(): R2Credentials {
  // First, try embedded credentials (from build time - your .env values)
  if (EMBEDDED_CREDENTIALS) {
    return EMBEDDED_CREDENTIALS;
  }

  // Fall back to environment variables (for development or if user wants to override)
  const endpoint = process.env["R2_ENDPOINT"];
  const accessKey = process.env["R2_ACCESS_KEY"];
  // Support both R2_SECRET_ACCESS_KEY (AWS S3 standard) and R2_SECRET_KEY (shorter name)
  const secretKey = process.env["R2_SECRET_ACCESS_KEY"] || process.env["R2_SECRET_KEY"];
  const bucket = process.env["R2_BUCKET"] ?? "pushenv";

  if (!endpoint || !accessKey || !secretKey) {
    throw new Error(
      "R2 credentials not configured. This package should have embedded credentials.\n" +
      "If you're running from source, set R2_ENDPOINT, R2_ACCESS_KEY, and R2_SECRET_KEY environment variables."
    );
  }

  return {
    endpoint,
    accessKey,
    secretKey,
    bucket,
  };
}

